# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160610_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Model'),
        ),
    ]
