# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160610_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='checkout_status',
            new_name='checked_out',
        ),
    ]
