# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160610_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
