# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_status_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Group'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Student'),
        ),
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
